version: "3.7"

networks:
  webnet:
    driver: overlay
    attachable: true # Needed in order to run custom commands in the container
services:
  web:
    image: transactions_mono:0.1.0
    build: "."
    env_file:
      - config/docker.env
    ports:
      - "8081:4000"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  db:
    image: mdillon/postgis
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
    volumes:
      - "~/postgres-mono-data:/var/lib/postgresql/data"
    env_file:
      - config/docker.env
    networks:
      - webnet
    ports:
      - 5432:5432
